language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2 ruby-rspec" -g "yast-rake gettext"
script:
    - rake check:syntax
    - rake check:pot
    - sudo rake install
    - rake test:unit check

